### ISSUE TITLE
list of (potential) initial members

### ISSUE THREAD

**Issue by sup** [nodejs/diversity#12]
as seen on https://nodejs.org/en/about/working-groups/#starting-a-wg, a WG needs to have initial members in order to be established (and at least 3, but i don't think that's a problem here). so i'll keep a list of everyone who wants to join the WG at initiation, and some basic info about them, if that's okay with everyone.

just comment with your full name, and i'll add you.

(@nodejs/diversity is this ok to do?)

**Comment by ashleygwilliams** [comment]
question... why nationality? 

i think we need to be careful about choosing/publicizing these things. nationality seems like it doesn't really make any sense at all, personally. especially when i think about the type of diversity i think this sort of initiative needs to foster.

**Comment by sup** [comment]
i've seen a couple of people talking about nationality in other threads, so i though it'd be wise to add it. but i see where you're coming from and it makes sense for inclusion purposes. sorry about that.

**Comment by ashleygwilliams** [comment]
s'all good. also, before you made this thread, i made a PR to @Trott's charter branch to add myself (he had emailed me about joining): https://github.com/Trott/diversity/pull/1

**Comment by sup** [comment]
:o i didn't see that at all, but with that, I suppose this thread is superfluous haha. i should also probably update my username on the charter fork
